# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and deploy docusaurus site 

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  AWS_REGION : "us-east-1"
  MAX_BRANCH_DEPLOYED: 5
  MAX_COMMIT_PER_BRANCH_DEPLOYED: 3
  BUCKET_NAME: "demo-docusaurus-multibranch-deploy"

permissions:
  id-token: write
  contents: write
  discussions: write
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Deploy
      id: deploy
      uses: dyadyaJora/s3-multibranch-deploy-preview@main
      with:
        aws_region: "${{ env.AWS_REGION }}"
        aws_assume_role: "${{ secrets.ASSUME_ROLE }}"
        aws_bucket: "${{ env.BUCKET_NAME }}"
        folder: "site"
    - name: Print LAB DOCS_LINK
      run: |
        echo "Docs deploy is available at ${{steps.deploy.outputs.preview_url}}"
